'use strict';
(()=>{
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:true}),board=$('#board');
let progress={},prefs={sound:false,assist:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};try{progress=JSON.parse(localStorage.getItem('lumaflow-cartoon-progress-v2')||'{}');prefs={...prefs,...JSON.parse(localStorage.getItem('lumaflow-prefs-v1')||'{}')};}catch{}
let index=0,world,points=[],drawing=false,pointerId=null,hintVisible=false,hintStep=0,demo=false,demoQueue=[],demoNext=0,lastState='',lastUI='',acc=0,last=0,scale=1,ox=0,oy=0,cw=0,ch=0,visible=true,paused=false,winShown=false,winRecorded=false,toastTimer,audioCtx=null,lastSound=0,ambient=0,mapChapter=0,strokeValid=true;
const C={navy:'#172b4d',cream:'#fff8df',coral:'#ee9475',teal:'#48c7c4',gold:'#f2c26a'};
function pathLength(ps){let n=0;for(let i=1;i<ps.length;i++)n+=FlowMath.dist(ps[i-1],ps[i]);return n;}
function savePrefs(){try{localStorage.setItem('lumaflow-prefs-v1',JSON.stringify(prefs));}catch{}}
function sound(kind){if(!prefs.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const t=audioCtx.currentTime,ns=kind==='win'?[523.25,659.25,783.99,1046.5]:kind==='gate'?[392,587.33]:kind==='drop'?[220,330]:kind==='water'?[800+Math.random()*300]:[420];ns.forEach((f,i)=>{const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type=kind==='gate'?'triangle':'sine';osc.frequency.setValueAtTime(f,t+i*.09);osc.frequency.exponentialRampToValueAtTime(f*.88,t+i*.09+.24);g.gain.setValueAtTime(0,t+i*.09);g.gain.linearRampToValueAtTime(kind==='water'?.012:.055,t+i*.09+.015);g.gain.exponentialRampToValueAtTime(.0001,t+i*.09+.45);osc.connect(g).connect(audioCtx.destination);osc.start(t+i*.09);osc.stop(t+i*.09+.5);});}catch{}}
function load(i){cancelDrawing();world?.destroy();index=Math.max(0,Math.min(49,i));world=new FlowWorld(FLOW_LEVELS[index],17+index);points=[];hintVisible=false;hintStep=0;demo=false;demoQueue=[];winShown=false;winRecorded=false;lastState='';lastUI='';acc=0;$('#result').hidden=true;$('#dropLineBtn').hidden=true;const l=world.level,ch=FLOW_CHAPTERS[l.chapter];$('#app').className=l.theme;$('#levelName').textContent=l.name;$('#levelNumber').innerHTML='<b>'+String(index+1).padStart(2,'0')+'</b><span>/50</span>';$('#chapterLabel').textContent=String(l.chapter+1).padStart(2,'0')+' · '+ch.name;$('#ruleText').textContent=l.rule;updateHUD();}
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function updateHUD(){if(!world)return;const ink=Math.max(0,Math.round(100-(world.ink+pathLength(points))/world.level.ink*100)),fills=world.cups.map(c=>Math.min(100,Math.floor(c.collected/c.target*100))),key=[ink,world.strokes.length,world.state,...fills,drawing,demo,points.length].join('/');if(key===lastUI)return;lastUI=key;$('#inkBar').style.width=ink+'%';$('#inkValue').textContent=ink+'%';$('#strokeCount').textContent=world.strokes.length+' / '+world.maxStrokes+' 本';$('#fillText').textContent=fills.join('% · ')+'%';$('#undoBtn').disabled=world.state!=='planning'||(!world.strokes.length&&!points.length)||demo;$('#pourBtn').disabled=world.state!=='planning'||drawing||demo;$('#pourBtn span').textContent=world.state==='flowing'?'流れてる！':world.state==='settling'?'もうすぐ！':'水を流す';
 const s=world.state;let text=prefs.assist?'点を置き、最後に「この線を落とす」。':'描いて、離して、準備ができたら。';if(world.strokes.length&&s==='planning')text=world.strokes.length<world.maxStrokes?'もう一筆？ それとも、水を流してみる？':'準備はできた？ 水を流して確かめよう。';if(s==='settling')text='さあ、あなたのアイデアを試そう！';if(s==='flowing')text=world.cups.length>1?'ふたりとも満たせるかな？':'いいぞ、水の行方を見守ろう。';if(s==='won')text='そのひらめき、大正解！';if(s==='lost')text='もう少し！形を変えて試してみよう。';if(demo&&s==='planning')text='お手本：線を落とす順番にも注目。';$('#instruction').textContent=text;
 if(world.collected>0&&world.time-lastSound>.3){sound('water');lastSound=world.time;}if(lastState!==s){lastState=s;}
}
function stars(){return world.ink<=world.level.parInk*1.12?3:world.ink<=world.level.parInk*1.3?2:1;}
function finish(){if(winShown)return;winShown=true;const won=world.state==='won';$('#resultMascot').hidden=!won;$('#resultEyebrow').textContent=demo?'WATCH & WONDER':won?'NICE IDEA!':'ONE MORE IDEA';$('#resultTitle').textContent=demo?'なるほど、こうつなぐ！':won?(index===49?'最後のひらめき！':'ひらめいた！'):'惜しい、もう一工夫！';$('#resultStars').textContent=won?'★'.repeat(stars())+'☆'.repeat(3-stars()):'↺';$('#resultCopy').textContent=demo?'今度はあなたのアイデアで挑戦しよう。':won?'水たちも、にっこり。次はどんな仕掛けかな？':'線の形、重さ、置く順番。どこを変えてみよう？';$('#nextBtn').textContent=demo?'自分でやってみる':won?(index===49?'ステージマップへ':'次のステージへ'):'もう一度描く';$('#againBtn').hidden=!won||demo;$('#result').hidden=false;if(won)sound('win');}
function cancelDrawing(e){if(e&&e.pointerId!==pointerId)return;$('#dropLineBtn').hidden=true;const id=pointerId;pointerId=null;drawing=false;points=[];if(id!==null&&canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);if(world)updateHUD();}
function showDialog(id){cancelDrawing();$('#dropLineBtn').hidden=true;paused=true;$(id).showModal();}
function drawMap(){const ch=FLOW_CHAPTERS[mapChapter];$('#mapChapterName').textContent=ch.name;$('#mapChapterEn').textContent=ch.en;$('#chapterTabs').replaceChildren();FLOW_CHAPTERS.forEach((c,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.setAttribute('role','tab');b.setAttribute('aria-label',c.name);b.setAttribute('aria-selected',String(i===mapChapter));b.onclick=()=>{mapChapter=i;drawMap();};$('#chapterTabs').append(b);});$('#levelGrid').replaceChildren();FLOW_LEVELS.slice(mapChapter*10,mapChapter*10+10).forEach((l,j)=>{const i=mapChapter*10+j,b=document.createElement('button');b.className='level-tile'+(i===index?' current':'')+(progress[i]?' done':'');b.setAttribute('aria-label','ステージ'+l.id+' '+l.name);b.innerHTML='<span>'+String(l.id).padStart(2,'0')+'</span><span class="rating">'+(progress[i]?'★'.repeat(progress[i])+'☆'.repeat(3-progress[i]):'・・・')+'</span>';b.onclick=()=>{$('#mapDialog').close();load(i);};$('#levelGrid').append(b);});}
function showMap(){mapChapter=world.level.chapter;$('#journeyCount').textContent=Object.keys(progress).filter(k=>progress[k]>0).length+' / 50 クリア　·　'+Object.values(progress).reduce((n,s)=>n+(Number(s)||0),0)+' ★';drawMap();showDialog('#mapDialog');}
$('#mapBtn').onclick=showMap;$('#levelNumber').onclick=showMap;$('#settingsBtn').onclick=()=>showDialog('#settingsDialog');$('#retryBtn').onclick=()=>{load(index);sound('draw');};$('#undoBtn').onclick=()=>{if(prefs.assist&&points.length){points.pop();$('#dropLineBtn').hidden=points.length<2;lastUI='';updateHUD();return;}cancelDrawing();if(world.undo()){winShown=false;lastUI='';lastState='';sound('draw');updateHUD();}};$('#pourBtn').onclick=()=>{if(points.length>1){toast('まず描いている線を完成させよう');return;}if(world.pour()){hintVisible=false;sound('drop');updateHUD();}};$('#againBtn').onclick=()=>load(index);$('#nextBtn').onclick=()=>{if(demo||world.state==='lost')load(index);else if(index===49)showMap();else load(index+1);};
function hintCopy(){const h=world.level.hints;$('#hintStep').textContent='HINT '+(hintStep+1)+' / 3';$('#hintText').textContent=hintStep<2?h[hintStep]:'線の形と、落とす順番を点線で表示できます。あなたらしい解き方も探してみよう。';$('#moreHintBtn').textContent=hintStep<2?'もう一つヒント':'線の形を見る';}
$('#hintBtn').onclick=()=>{hintCopy();showDialog('#hintDialog');};$('#moreHintBtn').onclick=()=>{if(hintStep<2){hintStep++;hintCopy();return;}$('#hintDialog').close();if(world.state!=='planning')load(index);hintVisible=true;toast('番号の順に線を落としてみよう');};$('#demoBtn').onclick=()=>{$('#hintDialog').close();load(index);demo=true;demoQueue=world.level.solutions.map(ps=>ps.map(p=>({...p})));demoNext=world.time+.4;};
for(const [id,key]of [['soundToggle','sound'],['assistToggle','assist'],['motionToggle','reduced']]){const el=$('#'+id);el.checked=prefs[key];el.onchange=e=>{prefs[key]=e.target.checked;savePrefs();if(key==='sound')sound('draw');if(key==='assist'){cancelDrawing();$('#dropLineBtn').hidden=true;lastUI='';updateHUD();}};}
for(const d of document.querySelectorAll('dialog')){d.querySelector('.close').onclick=()=>d.close();d.addEventListener('close',()=>{paused=false;last=performance.now();acc=0;});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
function resize(){const r=board.getBoundingClientRect();cw=r.width;ch=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min(cw/390,ch/570);ox=(cw-390*scale)/2;oy=(ch-570*scale)/2;}
new ResizeObserver(resize).observe(board);function local(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale};}
function addPoint(p){if(p.x<10||p.x>380||p.y<36||p.y>545)return;const lp=points.at(-1);if(lp&&FlowMath.dist(lp,p)<3)return;const length=pathLength(points);if(lp&&length+FlowMath.dist(lp,p)>world.level.ink-world.ink){const rem=world.level.ink-world.ink-length,dd=FlowMath.dist(lp,p);if(rem>.5)points.push({x:lp.x+(p.x-lp.x)*rem/dd,y:lp.y+(p.y-lp.y)*rem/dd});return;}if(points.length<220)points.push(p);strokeValid=points.length<2||!world.validate(points);}
canvas.addEventListener('pointerdown',e=>{if(world.state!=='planning'||paused||demo||pointerId!==null)return;e.preventDefault();if(world.strokes.length>=world.maxStrokes){toast('線はここまで。一筆戻すか、水を流してみよう');return;}const p=local(e);if(!world.allowed(p)){toast('物に重ならない場所から描こう');return;}if(prefs.assist){addPoint(p);$('#dropLineBtn').hidden=points.length<2;updateHUD();return;}pointerId=e.pointerId;canvas.setPointerCapture(pointerId);points=[];drawing=true;addPoint(p);sound('draw');updateHUD();});
canvas.addEventListener('pointermove',e=>{if(!drawing||e.pointerId!==pointerId)return;e.preventDefault();for(const ev of e.getCoalescedEvents?.()||[e])addPoint(local(ev));updateHUD();});
function commit(){if(points.length<2){points=[];updateHUD();return;}const r=world.draw(points);if(!r.ok)toast(r.error);else sound('drop');points=[];$('#dropLineBtn').hidden=true;updateHUD();}
canvas.addEventListener('pointerup',e=>{if(e.pointerId!==pointerId)return;addPoint(local(e));drawing=false;pointerId=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);commit();});canvas.addEventListener('pointercancel',cancelDrawing);canvas.addEventListener('lostpointercapture',e=>{if(drawing)cancelDrawing(e);});$('#dropLineBtn').onclick=commit;
document.addEventListener('visibilitychange',()=>{visible=!document.hidden;last=performance.now();acc=0;if(!visible){cancelDrawing();audioCtx?.suspend();}});
function line(ps,color,width){if(!ps.length)return;ctx.beginPath();ctx.moveTo(ps[0].x,ps[0].y);for(let i=1;i<ps.length;i++)ctx.lineTo(ps[i].x,ps[i].y);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=width;ctx.strokeStyle=color;ctx.stroke();}
function round(x,y,w,h,r,fill,stroke=true){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=C.navy;ctx.lineWidth=2.6;ctx.stroke();}}
function label(text,x,y,size=12,color=C.navy){ctx.textAlign='center';ctx.fillStyle=color;ctx.font='bold '+size+'px -apple-system,sans-serif';ctx.fillText(text,x,y);}
function stone(s){if(!s.w||!s.active||s.kind==='gate'||s.kind==='button-base')return;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle||0);const w=s.w,h=s.h;round(-w/2,-h/2+3,w,h,4,'#203754');const fill=s.kind==='drain'?'#e98b7c':s.kind==='plinth'?'#f4c877':'#f4cba2';round(-w/2,-h/2,w,h,4,fill);ctx.strokeStyle='#fff4dc';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-w/2+5,-h/2+4);ctx.lineTo(w/2-5,-h/2+4);ctx.stroke();if(s.kind==='drain'){ctx.save();ctx.beginPath();ctx.rect(-w/2+3,-h/2+3,w-6,h-6);ctx.clip();ctx.strokeStyle=C.navy;ctx.lineWidth=3;for(let x=-w/2;x<w/2;x+=9){ctx.beginPath();ctx.moveTo(x,-h/2);ctx.lineTo(x+9,h/2);ctx.stroke();}ctx.restore();}else if(w>40){ctx.strokeStyle='#ab826966';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-w/2+9,2);ctx.lineTo(w/2-9,2);ctx.stroke();}ctx.restore();}
function cupPath(c,inset=0){const l=c.x-c.w/2+inset,r=c.x+c.w/2-inset,b=c.y+c.h;ctx.beginPath();ctx.moveTo(l,c.y);ctx.lineTo(l+9,b-5);ctx.quadraticCurveTo(l+10,b,l+15,b);ctx.lineTo(r-15,b);ctx.quadraticCurveTo(r-10,b,r-9,b-5);ctx.lineTo(r,c.y);ctx.closePath();}
function cup(c,t){const b=c.y+c.h,fill=Math.min(1.1,c.collected/c.target),surface=b-7-fill*(c.h-28),happy=fill>=1;ctx.save();cupPath(c);ctx.fillStyle='#fff8dfee';ctx.fill();ctx.save();cupPath(c,3);ctx.clip();if(fill>0){ctx.fillStyle=happy?'#67d9c4':'#68d1d4';ctx.beginPath();ctx.moveTo(c.x-c.w/2,surface);for(let x=c.x-c.w/2;x<c.x+c.w/2+2;x+=3)ctx.lineTo(x,surface+Math.sin(x*.09-t*4)*(prefs.reduced?.3:1.8));ctx.lineTo(c.x+c.w/2,b+5);ctx.lineTo(c.x-c.w/2,b+5);ctx.closePath();ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#eaffdf';ctx.stroke();}ctx.restore();ctx.strokeStyle=C.navy;ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(c.x-c.w/2,c.y);ctx.lineTo(c.x-c.w/2+9,b-5);ctx.quadraticCurveTo(c.x-c.w/2+10,b,c.x-c.w/2+15,b);ctx.lineTo(c.x+c.w/2-15,b);ctx.quadraticCurveTo(c.x+c.w/2-10,b,c.x+c.w/2-9,b-5);ctx.lineTo(c.x+c.w/2,c.y);ctx.stroke();ctx.setLineDash([4,4]);ctx.lineWidth=1.4;ctx.strokeStyle='#d97f61';ctx.beginPath();ctx.moveTo(c.x-c.w/2+5,c.y+21);ctx.lineTo(c.x+c.w/2-5,c.y+21);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#fffdf1';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(c.x-c.w/2+8,c.y+29);ctx.lineTo(c.x-c.w/2+11,c.y+46);ctx.stroke();const ey=b-28;ctx.fillStyle=C.navy;for(const x of [c.x-10,c.x+10]){if(happy){ctx.beginPath();ctx.arc(x,ey+2,3,Math.PI,Math.PI*2);ctx.lineWidth=2;ctx.strokeStyle=C.navy;ctx.stroke();}else{ctx.beginPath();ctx.ellipse(x+(world.state==='flowing'?Math.sin(t)*.7:0),ey,2.2,3.2,0,0,Math.PI*2);ctx.fill();}}ctx.fillStyle='#f3a293';for(const x of [c.x-18,c.x+18]){ctx.beginPath();ctx.ellipse(x,ey+6,4,2.1,0,0,Math.PI*2);ctx.fill();}ctx.beginPath();if(happy){ctx.arc(c.x,ey+9,5,0,Math.PI);ctx.closePath();ctx.fillStyle=C.navy;ctx.fill();}else{ctx.moveTo(c.x-4,ey+10);ctx.quadraticCurveTo(c.x,ey+13,c.x+4,ey+10);ctx.strokeStyle=C.navy;ctx.lineWidth=1.5;ctx.stroke();}label(happy?'OK!':Math.min(100,Math.floor(fill*100))+'%',c.x,c.y-12,12,happy?'#167c7b':C.navy);ctx.restore();}
function source(s,t){const rem=1-world.emitted/world.total,w=Math.max(43,(s.spread||6)+24);ctx.save();ctx.translate(s.x,s.y);round(-w/2,-23,w,34,8,'#f39179');round(-w/2+5,-17,w-10,19,4,'#fff6d9');ctx.save();ctx.beginPath();ctx.rect(-w/2+7,-15,w-14,15);ctx.clip();ctx.fillStyle='#56caca';ctx.fillRect(-w/2+7,0-15*rem,w-14,15*rem);ctx.restore();round(-Math.max(7,(s.spread||6)/2),7,Math.max(14,s.spread||6),10,3,'#f2cb80');ctx.fillStyle=C.navy;ctx.beginPath();ctx.ellipse(0,17,Math.max(5,(s.spread||6)/2-2),2,0,0,Math.PI*2);ctx.fill();if(world.state==='planning'){ctx.fillStyle='#55bcbf';ctx.beginPath();ctx.ellipse(0,25+(prefs.reduced?0:Math.sin(t*2)*1.5),2.5,3.6,0,0,Math.PI*2);ctx.fill();}ctx.restore();}
function mechanics(t){for(const z of world.level.winds||[]){ctx.save();ctx.globalAlpha=.48;ctx.strokeStyle='#429aac';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.strokeRect(z.x-z.w/2,z.y-z.h/2,z.w,z.h);ctx.setLineDash([]);const sign=Math.sign(z.ax||1);for(let i=0;i<5;i++){const x=z.x-z.w/2+10+((i*19+(prefs.reduced?0:t*17*sign))%Math.max(1,z.w-20)+z.w-20)%(z.w-20),y=z.y-25+(i%3)*24;line([{x:x-7*sign,y},{x:x+6*sign,y}],'#357d9a',1.4);line([{x:x+2*sign,y:y-3},{x:x+6*sign,y},{x:x+2*sign,y:y+3}],'#357d9a',1.4);}ctx.restore();}
 for(const g of world.gates){const col=g.id==='A'?'#f5ca6b':'#b5a5dc';ctx.save();if(g.open){ctx.globalAlpha=.35;ctx.setLineDash([3,8]);line([{x:g.x-g.w/2,y:g.y},{x:g.x+g.w/2,y:g.y}],C.navy,1);ctx.setLineDash([]);label(g.id+' ✓',g.x-g.w/2+14,g.y-9,10);ctx.restore();continue;}round(g.x-g.w/2,g.y-(g.h||14)/2,g.w,g.h||14,3,col);ctx.save();ctx.beginPath();ctx.rect(g.x-g.w/2+2,g.y-(g.h||14)/2+1,g.w-4,(g.h||14)-2);ctx.clip();ctx.strokeStyle='#172b4d44';ctx.lineWidth=4;for(let x=g.x-g.w/2;x<g.x+g.w/2;x+=16){ctx.beginPath();ctx.moveTo(x,g.y-7);ctx.lineTo(x+10,g.y+7);ctx.stroke();}ctx.restore();round(g.x-10,g.y-11,20,22,5,col);label(g.id,g.x,g.y+4,12);ctx.restore();}
 for(const s of world.switches){round(s.x-(s.w||38)/2,s.y+2,s.w||38,14,4,'#eec4a1');round(s.x-12,s.y+(s.active?0:-4),24,s.active?7:11,4,s.active?'#6dc8ad':s.gate==='A'?'#f5ca6b':'#b5a5dc');label(s.active?'✓':s.gate,s.x,s.y-11,12,s.active?'#177666':C.navy);}
}
function render(t){ctx.clearRect(0,0,cw,ch);ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);for(const s of world.solids)if(s.kind!=='cup')stone(s);mechanics(t);for(const c of world.cups)cup(c,t);for(const s of world.level.sources||[world.level.source])source(s,t);
 if(hintVisible&&world.state==='planning'){world.level.solutions.forEach((ps,i)=>{ctx.save();ctx.setLineDash([6,8]);line(ps,'#ab6f5ea0',2.5);ctx.restore();const p=ps[0];round(p.x-9,p.y-24,18,18,6,'#fff7df');label(String(i+1),p.x,p.y-11,10);});}
 for(const s of world.strokes){const ps=world.strokePoints(s);line(ps,C.navy,9);line(ps,'#61c8b8',5.4);line(ps,'#b3edcd',1.1);}
 if(points.length){line(points,C.navy,9);line(points,strokeValid?'#6ad3be':'#f19379',5.5);const p=points.at(-1);ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.strokeStyle='#172b4d66';ctx.lineWidth=1;ctx.stroke();}
 ctx.save();ctx.lineCap='round';ctx.strokeStyle='#287895';ctx.lineWidth=5.2;ctx.beginPath();for(const p of world.drops){ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx*.007,p.y-p.vy*.007);}ctx.stroke();ctx.strokeStyle='#69d9dd';ctx.lineWidth=3.6;ctx.stroke();ctx.strokeStyle='#eff9deaa';ctx.lineWidth=1;ctx.stroke();ctx.restore();for(const p of world.sparks){const a=p.age/.5;ctx.beginPath();ctx.ellipse(p.x,p.y,2+a*7,1+a*2,0,0,Math.PI*2);ctx.strokeStyle='rgba(40,126,152,'+(1-a)*.5+')';ctx.lineWidth=1;ctx.stroke();}
 if(index===0&&world.state==='planning'&&!points.length&&!world.strokes.length&&!hintVisible){label('ここに、あなたのひと筆を。',195,136,13,'#768479');}
 if(world.state==='won'&&!prefs.reduced){const a=world.time-world.winAt;for(let i=0;i<32;i++){const theta=i*2.399,r=a*25+i%5*10,x=195+Math.cos(theta)*r,y=330-Math.sin(theta)*r-a*18;ctx.globalAlpha=Math.max(0,1-a*.15);ctx.fillStyle=[C.coral,C.teal,C.gold,'#9c9bdb'][i%4];ctx.save();ctx.translate(x,y);ctx.rotate(theta+a);ctx.fillRect(-2,-4,4,8);ctx.restore();}ctx.globalAlpha=1;}ctx.restore();}
function recordWin(){if(world.state!=='won'||demo||winRecorded)return;winRecorded=true;progress[index]=Math.max(Number(progress[index])||0,stars());try{localStorage.setItem('lumaflow-cartoon-progress-v2',JSON.stringify(progress));}catch{}}
function tick(){world.step();recordWin();if(demo&&world.state==='planning'&&world.time>=demoNext){if(demoQueue.length){const r=world.draw(demoQueue.shift());if(!r.ok){demoQueue=[];demo=false;toast('お手本をもう一度開いてください');return;}demoNext=world.time+1.2;}else world.pour();}}
function frame(now){requestAnimationFrame(frame);if(!last)last=now;const delta=Math.min((now-last)/1000,.08);last=now;if(!visible)return;if(!paused){acc+=delta;let steps=0;while(acc>=1/120&&steps<10){tick();acc-=1/120;steps++;}if(steps===10)acc=0;updateHUD();if(world.state==='won'&&world.time-world.winAt>1.1||world.state==='lost')finish();}ambient+=delta;render(ambient);}
load(0);resize();requestAnimationFrame(frame);
if(new URLSearchParams(location.search).has('qa'))window.__lumaQA={load:(i)=>load(i),draw:ps=>world.draw(ps),pour:()=>world.pour(),undo:()=>world.undo(),step:n=>{for(let i=0;i<n;i++)tick();updateHUD();render(ambient);},snapshot:()=>world.snapshot(),layout:()=>({scale,ox,oy,cw,ch}),level:()=>world.level,showMap,render:()=>render(ambient)};
})();
