(function(root){
'use strict';
const M=typeof module!=='undefined'?require('./vendor/matter.min.js'):root.Matter;
const W=390,H=570,DT=1/120,R=2.7;
// Plans live outside the simulation: tokens never become part of undo snapshots.
const savedPlans=new WeakMap();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function nearest(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return{x:a.x+t*dx,y:a.y+t*dy};}
function simplify(ps,eps=1.5){if(ps.length<3)return ps;let md=0,j=0;for(let i=1;i<ps.length-1;i++){const d=dist(ps[i],nearest(ps[i],ps[0],ps.at(-1)));if(d>md){md=d;j=i;}}return md>eps?simplify(ps.slice(0,j+1),eps).slice(0,-1).concat(simplify(ps.slice(j),eps)):[ps[0],ps.at(-1)];}
class FlowWorld{
 constructor(level,seed=17){
 this.level=level;this.seed=seed>>>0;this.engine=M.Engine.create({positionIterations:8,velocityIterations:6,enableSleeping:true});this.engine.gravity.y=1;this.engine.gravity.scale=.0009;
 this.solids=[];this.edges=[];this.strokes=[];this.drops=[];this.sparks=[];this.switches=[];this.gates=[];this.history=[];this.ticks=0;this.time=0;this.pourAt=Infinity;this.emitted=0;this.collected=0;this.lost=0;this.drained=0;this.state='planning';this.ink=0;this.winAt=0;this.total=level.total||400;this.maxStrokes=level.maxStrokes||3;this.cups=(level.cups||[level.cup]).map((c,i)=>({...c,id:i,collected:0,target:c.target||level.target||190}));this.target=this.cups.reduce((n,c)=>n+c.target,0);
 this.relays=(level.relays||[]).map((r,i)=>({...r,id:r.id||`R${i+1}`,r:r.r||18,minHits:Math.max(1,Math.floor(r.minHits||3)),required:r.required!==false,hits:0,active:false,triggeredAt:null,seenIds:new Set()}));
 for(const p of level.platforms||[])this.addRect(p.x,p.y,p.w,p.h,p.angle||0,p.kind||'stone');
 for(const c of this.cups){const l=c.x-c.w/2,r=c.x+c.w/2,b=c.y+c.h;this.addSegment({x:l,y:c.y},{x:l+9,y:b},7,'cup',c.id);this.addSegment({x:r,y:c.y},{x:r-9,y:b},7,'cup',c.id);this.addSegment({x:l+9,y:b},{x:r-9,y:b},8,'cup',c.id);this.addRect(c.x,b+16,c.w+18,21,0,'plinth');}
 for(const g of level.gates||[]){const s=this.addRect(g.x,g.y,g.w,g.h||14,0,'gate');s.gateId=g.id;for(const e of s.edges)e.gateId=g.id;this.gates.push({...g,solid:s,open:false});}
 for(const s of level.switches||[]){this.addRect(s.x,s.y+9,s.w||38,14,0,'button-base');this.switches.push({...s,held:0,active:false});}
 for(const d of level.drains||[])this.addRect(d.x,d.y,d.w,d.h||12,0,'drain');
 }
 rand(){this.seed=(Math.imul(1664525,this.seed)+1013904223)>>>0;return this.seed/4294967296;}
 addRect(x,y,w,h,angle=0,kind='stone'){const body=M.Bodies.rectangle(x,y,w,h,{isStatic:true,angle,friction:.8,restitution:0}),s={body,x,y,w,h,angle,kind,active:true,edges:[]};M.Composite.add(this.engine.world,body);this.solids.push(s);const vs=body.vertices;for(let i=0;i<vs.length;i++){const e={a:{x:vs[i].x,y:vs[i].y},b:{x:vs[(i+1)%vs.length].x,y:vs[(i+1)%vs.length].y},r:0,solid:s};s.edges.push(e);this.edges.push(e);}return s;}
 addSegment(a,b,width,kind,cupId){const body=M.Bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,dist(a,b),width,{isStatic:true,angle:Math.atan2(b.y-a.y,b.x-a.x),friction:.8}),s={body,kind,cupId,active:true,edges:[]};M.Composite.add(this.engine.world,body);this.solids.push(s);const e={a,b,r:width/2,solid:s};s.edges.push(e);this.edges.push(e);return s;}
 strokePoints(s){const c=Math.cos(s.body.angle),n=Math.sin(s.body.angle);return s.local.map(p=>({x:s.body.position.x+p.x*c-p.y*n,y:s.body.position.y+p.x*n+p.y*c}));}
 allowed(p){if(p.x<10||p.x>380||p.y<36||p.y>545)return false;for(const z of this.level.noDraw||[])if(Math.abs(p.x-z.x)<z.w/2&&Math.abs(p.y-z.y)<z.h/2)return false;for(const s of this.solids)if(s.active&&M.Vertices.contains(s.body.vertices,p))return false;for(const e of this.edges)if(e.solid.active&&dist(p,nearest(p,e.a,e.b))<4.5+e.r)return false;for(const s of this.strokes){const ps=this.strokePoints(s);for(let i=1;i<ps.length;i++)if(dist(p,nearest(p,ps[i-1],ps[i]))<8)return false;}for(const s of this.level.sources||[this.level.source])if(dist(p,s)<24)return false;return true;}
 validate(ps){if(!Array.isArray(ps)||ps.length<2)return 'もう少し長く描いてみよう';if(ps.length>250||ps.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)))return '線を描き直そう';if(this.strokes.length>=this.maxStrokes)return '線の数がいっぱい。一筆戻すか、リトライしよう';let len=0;for(let i=1;i<ps.length;i++){const a=ps[i-1],b=ps[i],d=dist(a,b);len+=d;for(let j=0;j<=Math.ceil(d/3);j++){const t=j/Math.max(1,Math.ceil(d/3));if(!this.allowed({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}))return '物に重ならない場所から描こう';}}if(len<18)return 'もう少し長く描いてみよう';if(this.ink+len>this.level.ink+1)return 'インクが足りない！短い形を考えよう';return null;}
 draw(ps){if(this.state!=='planning')return{ok:false,error:'リトライして描き直そう'};let error=this.validate(ps);if(error)return{ok:false,error};let p=simplify(ps);if(this.validate(p))p=ps.map(a=>({...a}));
 const history=this.history;this.history=[];let before;try{before=structuredClone(this);}finally{this.history=history;}
 const parts=[];let len=0;for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],d=dist(a,b);len+=d;if(d<.1)continue;parts.push(M.Bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,d+1,7,{angle:Math.atan2(b.y-a.y,b.x-a.x)}));}for(const a of p)parts.push(M.Bodies.circle(a.x,a.y,3.5,{},8));const body=M.Body.create({parts,friction:.85,frictionStatic:1.5,frictionAir:.012,restitution:.02,density:.004,sleepThreshold:100});
 // Matter sums local part inertia but omits offsets from the compound centre.
 // Apply the parallel-axis theorem in Matter's existing inertia units, so hand
 // jitter / many short segments cannot turn a long rod into an unstable spinner.
 const inertia=body.parts.slice(1).reduce((sum,part)=>sum+part.inertia+M.Body._inertiaScale*part.mass*((part.position.x-body.position.x)**2+(part.position.y-body.position.y)**2),0);
 M.Body.setInertia(body,inertia);
 const local=p.map(a=>({x:a.x-body.position.x,y:a.y-body.position.y}));M.Composite.add(this.engine.world,body);this.strokes.push({body,local,original:p,length:len,createdAt:this.time});this.ink+=len;this.history.push(before);return{ok:true};}
 undo(){if(this.state!=='planning'||!this.history.length)return false;const snap=this.history.pop(),history=this.history;M.Composite.clear(this.engine.world,false);M.Engine.clear(this.engine);Object.assign(this,snap);this.history=history;return true;}
 capturePlan(){if(this.state!=='planning')return null;const token=Object.freeze({kind:'FlowWorldPlan-v1'});savedPlans.set(token,{owner:this,state:structuredClone(this)});return token;}
 restorePlan(token){const plan=token&&savedPlans.get(token);if(!plan||plan.owner!==this)return false;const restored=structuredClone(plan.state);M.Composite.clear(this.engine.world,false);M.Engine.clear(this.engine);Object.assign(this,restored);return true;}
 updateRelays(p,previous){for(const relay of this.relays){if(relay.active||relay.seenIds.has(p.id)||dist({x:relay.x,y:relay.y},nearest({x:relay.x,y:relay.y},previous,p))>relay.r+R)continue;relay.seenIds.add(p.id);relay.hits++;if(relay.hits>=relay.minHits){relay.active=true;relay.triggeredAt=this.time;for(const id of relay.gates||(relay.gate?[relay.gate]:[]))this.openGate(id);}}}
 pour(){if(this.state!=='planning')return false;this.state='settling';this.pourAt=this.time+.8;return true;}
 openGate(id){for(const g of this.gates){if(g.id!==id||g.open)continue;g.open=true;g.solid.active=false;M.Composite.remove(this.engine.world,g.solid.body);for(const s of this.strokes)M.Sleeping.set(s.body,false);}}
 updateSwitches(){for(const sw of this.switches){if(sw.active)continue;let pressed=false;for(const s of this.strokes){if(s.length<(sw.minLength||0))continue;const ps=this.strokePoints(s);for(let i=1;i<ps.length;i++){if(dist({x:sw.x,y:sw.y-1},nearest({x:sw.x,y:sw.y-1},ps[i-1],ps[i]))<9){pressed=true;break;}}if(pressed)break;}sw.held=pressed?sw.held+DT:0;if(sw.held>=.08){sw.active=true;for(const id of sw.gates||[sw.gate])this.openGate(id);}}}
 step(){this.ticks++;this.time+=DT;M.Engine.update(this.engine,1000*DT);this.updateSwitches();if(this.state==='settling'&&this.time>=this.pourAt)this.state='flowing';
 if(this.state==='flowing'&&this.emitted<this.total){const wanted=Math.min(this.total,Math.floor((this.time-this.pourAt)*(this.level.rate||60)));while(this.emitted<wanted){const sources=this.level.sources||[this.level.source],s=sources[this.emitted%sources.length];this.drops.push({x:s.x+(this.rand()-.5)*(s.spread||6),y:s.y+17,vx:(this.rand()-.5)*10,vy:20+this.rand()*8,age:0,inside:0,entryCupId:null,id:this.emitted});this.emitted++;}}
 const edges=this.edges.filter(e=>e.solid.active);for(const s of this.strokes){const ps=this.strokePoints(s);for(let i=1;i<ps.length;i++)edges.push({a:ps[i-1],b:ps[i],r:3.5,body:s.body});}
 for(let k=this.drops.length-1;k>=0;k--){const p=this.drops[k];p.age+=DT;const previous={x:p.x,y:p.y};p.vy+=630*DT;for(const f of this.level.winds||[])if(Math.abs(p.x-f.x)<f.w/2&&Math.abs(p.y-f.y)<f.h/2){p.vx+=(f.ax||0)*DT;p.vy+=(f.ay||0)*DT;}const speed=Math.hypot(p.vx,p.vy);if(speed>440){p.vx*=440/speed;p.vy*=440/speed;}p.x+=p.vx*DT;p.y+=p.vy*DT;
 for(let pass=0;pass<2;pass++)for(const e of edges){if(p.x<Math.min(e.a.x,e.b.x)-10||p.x>Math.max(e.a.x,e.b.x)+10||p.y<Math.min(e.a.y,e.b.y)-10||p.y>Math.max(e.a.y,e.b.y)+10)continue;const q=nearest(p,e.a,e.b),dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy),rad=R+e.r,old=nearest(previous,e.a,e.b),odx=previous.x-old.x,ody=previous.y-old.y,od=Math.hypot(odx,ody),crossed=odx*dx+ody*dy<0&&od>0,ex=e.b.x-e.a.x,ey=e.b.y-e.a.y,elen2=ex*ex+ey*ey,side0=(previous.x-e.a.x)*ey-(previous.y-e.a.y)*ex,side1=(p.x-e.a.x)*ey-(p.y-e.a.y)*ex,hitT=side0/(side0-side1||1),ix=previous.x+(p.x-previous.x)*hitT,iy=previous.y+(p.y-previous.y)*hitT,proj=((ix-e.a.x)*ex+(iy-e.a.y)*ey)/(elen2||1),swept=side0*side1<0&&hitT>=0&&hitT<=1&&proj>=0&&proj<=1;if(d>=rad&&!swept)continue;let nx=dx/(d||1),ny=dy/(d||1);if(crossed||swept){nx=odx/(od||1);ny=ody/(od||1);}if(d<.0001&&!swept){const v=dist(e.a,e.b)||1;nx=(e.b.y-e.a.y)/v;ny=-(e.b.x-e.a.x)/v;}p.x=(swept?ix:q.x)+nx*(rad+.03);p.y=(swept?iy:q.y)+ny*(rad+.03);let sx=0,sy=0;if(e.body){sx=e.body.velocity.x*60-e.body.angularVelocity*60*(q.y-e.body.position.y);sy=e.body.velocity.y*60+e.body.angularVelocity*60*(q.x-e.body.position.x);}const vn=(p.vx-sx)*nx+(p.vy-sy)*ny;if(vn<0){p.vx-=1.03*vn*nx;p.vy-=1.03*vn*ny;}p.vx*=.997;p.vy*=.997;}
 this.updateRelays(p,previous);
 let sink=false;for(const d of this.level.drains||[])if(Math.abs(p.x-d.x)<d.w/2+R&&Math.abs(p.y-d.y)<(d.h||12)/2+R+1){sink=true;break;}
 if(sink){this.drained++;this.lost++;this.drops.splice(k,1);continue;}
 let capture=null;for(const c of this.cups){if(previous.y<c.y+8&&p.y>=c.y+8){const t=(c.y+8-previous.y)/(p.y-previous.y),x=previous.x+(p.x-previous.x)*t;if(Math.abs(x-c.x)<c.w/2-7){p.entryCupId=c.id;p.inside=0;}}if(p.entryCupId!==c.id)continue;if(p.y<c.y-3){p.entryCupId=null;p.inside=0;continue;}const rel=(p.y-c.y)/c.h,inner=c.w/2-9*Math.max(0,rel)-7,inside=p.y>c.y+24&&p.y<c.y+c.h-3&&Math.abs(p.x-c.x)<inner;p.inside=inside?p.inside+DT:0;if(p.inside>.17){capture=c;break;}}
 if(capture){capture.collected++;this.collected++;this.sparks.push({x:p.x,y:Math.max(capture.y+12,capture.y+capture.h-8-capture.collected/capture.target*(capture.h-28)),age:0});this.drops.splice(k,1);}else if(p.y>H+30||p.x<-60||p.x>W+60||p.age>11){this.lost++;this.drops.splice(k,1);}}
 for(let i=this.sparks.length-1;i>=0;i--){this.sparks[i].age+=DT;if(this.sparks[i].age>.5)this.sparks.splice(i,1);}if(this.sparks.length>35)this.sparks.splice(0,this.sparks.length-35);
 if(this.state==='flowing'&&this.cups.every(c=>c.collected>=c.target)&&this.relays.every(r=>!r.required||r.active)){this.state='won';this.winAt=this.time;}
 const needed=this.cups.reduce((n,c)=>n+Math.max(0,c.target-c.collected),0);if(this.state==='flowing'&&(this.drops.length+this.total-this.emitted<needed||(this.emitted===this.total&&this.drops.length===0)))this.state='lost';
 }
 snapshot(){return{state:this.state,cups:this.cups.map(c=>({id:c.id,collected:c.collected,target:c.target})),collected:this.collected,target:this.target,emitted:this.emitted,lost:this.lost,drained:this.drained,live:this.drops.length,ink:this.ink,strokes:this.strokes.length,time:this.time,gates:this.gates.map(g=>({id:g.id,open:g.open})),relays:this.relays.map(r=>({id:r.id,hits:r.hits,minHits:r.minHits,required:r.required,active:r.active,triggeredAt:r.triggeredAt})),bodyCount:M.Composite.allBodies(this.engine.world).length,finite:this.drops.every(p=>Number.isFinite(p.x+p.y+p.vx+p.vy))&&this.strokes.every(s=>Number.isFinite(s.body.position.x+s.body.position.y+s.body.angle))};}
 destroy(){M.Composite.clear(this.engine.world,false);M.Engine.clear(this.engine);this.history=[];}
}
root.FlowWorld=FlowWorld;root.FlowMath={nearest,dist,simplify};if(typeof module!=='undefined')module.exports={FlowWorld,FlowMath:root.FlowMath};
})(typeof window!=='undefined'?window:globalThis);
