'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {FlowWorld}=require('../dist/physics.js'),M=require('../dist/vendor/matter.min.js');
function fixture(extra={}){return{source:{x:30,y:40},cup:{x:350,y:450,w:50,h:70},platforms:[{x:195,y:320,w:350,h:20}],ink:1000,maxStrokes:3,...extra};}
function world(material,beltSpeed){const l=fixture();Object.assign(l.platforms[0],{material,beltSpeed});return new FlowWorld(l);}
function drop(w,x=190,y=290,vx=0,vy=0){const p={id:w.emitted++,x,y,vx,vy,age:0,inside:0,entryCupId:null};w.drops.push(p);return p;}
function line(w){assert.equal(w.draw([{x:170,y:290},{x:210,y:290}]).ok,true);return w.strokes[0].body;}
function steps(w,n){for(let i=0;i<n;i++)w.step();}
test('gravityScale changes acceleration of both rods and water',()=>{const observations=[];for(const gravityScale of [0,.5,1]){const w=new FlowWorld(fixture({platforms:[],gravityScale}));const b=line(w),p=drop(w,100,100);steps(w,20);observations.push({rod:b.position.y-290,water:p.y-100});w.destroy();}assert.ok(Math.abs(observations[0].rod)<1e-9);assert.equal(observations[0].water,0);assert.ok(observations[1].rod<observations[2].rod*.6);assert.ok(observations[1].water<observations[2].water*.6);});
test('ice allows a landed rod to slide farther than normal ground',()=>{const travel=[];for(const material of ['stone','ice']){const w=world(material),b=line(w);steps(w,180);M.Sleeping.set(b,false);const x=b.position.x;M.Body.setVelocity(b,{x:1.5,y:0});steps(w,90);travel.push(b.position.x-x);w.destroy();}assert.ok(travel[1]>travel[0]+20,JSON.stringify(travel));});
test('rubber rebounds rods and water instead of absorbing the impact',()=>{const rebounds=[];for(const material of ['stone','rubber']){const w=world(material),b=line(w),p=drop(w,100,240,0,100);M.Body.setPosition(b,{x:b.position.x,y:190});let rod=0,water=0;for(let i=0;i<180;i++){w.step();rod=Math.min(rod,b.velocity.y);water=Math.min(water,p.vy);}rebounds.push({rod,water});w.destroy();}assert.ok(rebounds[1].rod<rebounds[0].rod-.3,JSON.stringify(rebounds));assert.ok(rebounds[1].water<rebounds[0].water-50,JSON.stringify(rebounds));});
test('belt direction transports both a supported rod and water',()=>{for(const beltSpeed of [-55,55]){const w=world('conveyor',beltSpeed),b=line(w),p=drop(w,100,290);const x=b.position.x,px=p.x;steps(w,180);assert.ok((b.position.x-x)*Math.sign(beltSpeed)>30,`rod belt ${beltSpeed}: ${b.position.x-x}`);assert.ok((p.x-px)*Math.sign(beltSpeed)>30,`water belt ${beltSpeed}: ${p.x-px}`);assert.ok(Math.abs(b.angularVelocity)<.04,'conveyor does not spin supported rod');w.destroy();}});
test('a belt cannot accelerate a rod or water before contact',()=>{const w=world('conveyor',55),b=line(w),p=drop(w,100,100);steps(w,5);assert.equal(b.velocity.x,0);assert.equal(p.vx,0);w.destroy();});
test('material and gravity state survives retry with deterministic contacts',()=>{const w=world('conveyor',-40);w.gravityScale=.65;w.engine.gravity.scale=.0009*.65;line(w);steps(w,80);const plan=w.capturePlan(),before=w.snapshot();steps(w,60);const after=w.snapshot(),position={...w.strokes[0].body.position};assert.equal(w.restorePlan(plan),true);assert.deepEqual(w.snapshot(),before);assert.equal(w.gravityScale,.65);assert.equal(w.solids[0].material,'conveyor');assert.equal(w.solids[0].beltSpeed,-40);steps(w,60);assert.deepEqual(w.snapshot(),after);assert.deepEqual(w.strokes[0].body.position,position);w.destroy();});
test('rubber impact cannot continually add energy to a resting rod',()=>{const w=world('rubber'),b=line(w);M.Body.setPosition(b,{x:b.position.x,y:190});steps(w,1800);assert.ok(b.position.y>300&&b.position.y<312,`rest height ${b.position.y}`);assert.ok(b.speed<.01,`speed ${b.speed}`);w.destroy();});
